[package]
name = "movie-barcode"
version = "0.1.0"
authors = ["Billy Main <wmain@netflix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.2"
rayon = "1.1.0"